  - name: creating user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"

  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creat an app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Remove Zip file
    ansible.builtin.file:
      path: /tmp/{{ comment }}.zip
      state: absent

  - name: Download application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
      dest: /tmp/{{ comment }}.zip
  
  - name: removing code
    ansible.builtin.command: rm -rf /app/*

  - name: unzipping code
    ansible.builtin.unarchive:
      src: /tmp/{{ comment }}.zip
      dest: /app
      remote_src: yes